import FormalLanglandsLab.Core.BasicNumberTheory
import FormalLanglandsLab.Core.ArithmeticFunctions
import FormalLanglandsLab.LFunctions.FormalDirichletSeries
import FormalLanglandsLab.Bridge.LanglandsPrototype
