import FormalLanglandsLab.Core.BasicNumberTheory
import FormalLanglandsLab.Core.ArithmeticFunctions
import FormalLanglandsLab.Core.MultiplicativeFunctions
import FormalLanglandsLab.Core.DirichletConvolution
import FormalLanglandsLab.Core.PrimeData
