import FormalLanglandsLab.Galois.GaloisRepresentations
import FormalLanglandsLab.Galois.FrobeniusTraces
import FormalLanglandsLab.Galois.GaloisLSeries
import FormalLanglandsLab.Galois.MatrixRepresentations
import FormalLanglandsLab.Galois.MatrixLSeries
import FormalLanglandsLab.Galois.MatrixCharacteristicData
import FormalLanglandsLab.Galois.CohomologicalRepresentations
